### ISSUE TITLE
Proxy Login Script Error in Running and some suggestions

### ISSUE THREAD

**Issue by ozym4nd145** [devclub-iitd/Scripts#1]
Running the release script of proxyLogin gives an error:
```
~/Downloads$ ./proxyLogin
panic: runtime error: index out of range

goroutine 1 [running]:
main.main()
	/home/shourya/proxyLogin/proxyLogin/proxyLogin.go:223 +0x1c1
```
Please take the arguments using something like argparse and display as help message.
Also, have alternate way of giving the credentials (maybe something like a text file? and interactive input) so that it does not get logged in the terminal history.

One more suggestion is to strip the binary to reduce its size.

One can also print these export message (or have a flag that prints them) after logging in:
```
export http_proxy="http://proxyXX.iitd.ac.in:3128"
export https_proxy="http://proxyXX.iitd.ac.in:3128"
export HTTP_PROXY="http://proxyXX.iitd.ac.in:3128"
export HTTPS_PROXY="http://proxyXX.iitd.ac.in:3128"
```
where XX is the appropriate category. This will help users in setting the annoying proxy variable if not already set.

Lastly, it will be helpful if we can skip the whole category input thing.

**Comment by ShouryaAggarwal** [comment]
Resolved.
